# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            sandcrawler.js
tagline:          'The server-side scraping companion.'
description:      'The server-side scraping companion.'
baseurl:          '/sandcrawler'

author:
  name:           'Yomguithereal'
  url:            https://github.com/Yomguithereal

# Custom vars
version:          0.0.1

sidebar:
  - url: 'quick_start'
    title: 'Quick Start'
  - sep
  - url: 'spider'
    title: 'Spider'
  - url: 'phantom_spider'
    title: 'Phantom Spider'
  - url: 'phantom_artoo'
    title: 'Phantom Artoo'
  - url: 'spawn'
    title: 'Spawning phantoms'
  - url: 'lifecycle'
    title: 'Lifecycle'
  - url: 'plugins'
    title: 'Plugins'
  - url: 'examples'
    title: 'Examples'
  - sep
  - url: 'changelog'
    title: 'Changelog'

github:
  repo:           https://github.com/medialab/sandcrawler

medialab:
  url:            'http://www.medialab.sciences-po.fr/'

links:
  artoo:          http://medialab.github.io/artoo/
